
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Mar  3 2025 10:57:28 IST (Mar  3 2025 05:27:28 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, mc_rb_fuse_vld_q, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  DFFR_X2 \skew_addr_cntr_reg[4] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_16), .Q (skew_addr_cntr_o[4]), .QN
       (n_0));
  DFFR_X2 \skew_addr_cntr_reg[1] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_13), .Q (skew_addr_cntr_o[1]), .QN
       (UNCONNECTED));
  DFFR_X2 \skew_addr_cntr_reg[3] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_11), .Q (skew_addr_cntr_o[3]), .QN
       (UNCONNECTED0));
  DFFR_X2 \skew_addr_cntr_reg[2] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_12), .Q (skew_addr_cntr_o[2]), .QN
       (UNCONNECTED1));
  DFFR_X2 \skew_addr_cntr_reg[0] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_15), .Q (skew_addr_cntr_o[0]), .QN
       (UNCONNECTED2));
  NOR2_X1 g478__2398(.A1 (n_10), .A2 (n_14), .ZN (n_16));
  NOR2_X1 g485__5107(.A1 (n_14), .A2 (skew_addr_cntr_o[0]), .ZN (n_15));
  NOR2_X1 g486__6260(.A1 (n_14), .A2 (n_3), .ZN (n_13));
  NOR2_X1 g487__4319(.A1 (n_14), .A2 (n_5), .ZN (n_12));
  NOR2_X1 g483__8428(.A1 (n_14), .A2 (n_9), .ZN (n_11));
  XNOR2_X1 g480__5526(.A (n_8), .B (skew_addr_cntr_o[4]), .ZN (n_10));
  NOR2_X1 g488__6783(.A1 (n_6), .A2 (n_2), .ZN (n_14));
  XNOR2_X1 g489__3680(.A (n_7), .B (skew_addr_cntr_o[3]), .ZN (n_9));
  AND2_X4 g490__1617(.A1 (n_7), .A2 (skew_addr_cntr_o[3]), .ZN (n_8));
  OAI22_X1 g491__2802(.A1 (n_1), .A2 (skew_addr_cntr_o[4]), .B1
       (mc_rb_fuse_vld_q), .B2 (mc_rb_ef1_svld_i), .ZN (n_6));
  XNOR2_X1 g493__1705(.A (n_4), .B (skew_addr_cntr_o[2]), .ZN (n_5));
  AND2_X4 g494__5122(.A1 (n_4), .A2 (skew_addr_cntr_o[2]), .ZN (n_7));
  XNOR2_X1 g496__8246(.A (skew_addr_cntr_o[0]), .B
       (skew_addr_cntr_o[1]), .ZN (n_3));
  NOR3_X1 g495__7098(.A1 (n_0), .A2 (skew_addr_cntr_o[3]), .A3
       (skew_addr_cntr_o[2]), .ZN (n_2));
  NOR4_X1 g492__6131(.A1 (skew_addr_cntr_o[2]), .A2
       (skew_addr_cntr_o[0]), .A3 (skew_addr_cntr_o[3]), .A4
       (skew_addr_cntr_o[1]), .ZN (n_1));
  DFFR_X2 mc_rb_fuse_vld_q_reg(.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (mc_rb_fuse_vld_i), .Q (UNCONNECTED3),
       .QN (mc_rb_fuse_vld_q));
  AND2_X4 g498__1881(.A1 (skew_addr_cntr_o[1]), .A2
       (skew_addr_cntr_o[0]), .ZN (n_4));
endmodule

