/*
 *    DESC: Generated by Tessent FastScan at Wed Apr 23 13:56:12 IST 2025
 */
module MGC_DFT_LIB_ALL ( DPRAM_16x4_Port__a_state , DPRAM_16x4_Port__ck_state , 
                         DPRAM_16x4_Port__web_state , DPRAM_16x4_Port__oeb_state , 
                         DPRAM_16x4_Port__csb_state , DPRAM_16x4_Port__i_state , 
                         DPRAM_16x4_Port__o_state , DPRAM_16x4_Port__ena_state , 
                         DPRAM_16x4_Port__blockIsSelected , 
                         DPRAM_16x4_Port__sh_a_error , 
                         DPRAM_16x4_Port__sh_web_error , 
                         DPRAM_16x4_Port__sh_ba_error , 
                         DPRAM_16x4_Port__sh_ck_error , 
                         DPRAM_16x4_Port__sh_csb_error , 
                         DPRAM_16x4_Port__sh_i_error , DPRAM_16x4_Port__WE , 
                         DPRAM_16x4_Port__CS , DPRAM_16x4_Port__memoryAddr , 
                         DPRAM_16x4_Port__memoryIn , DPRAM_16x4_Port__memoryOut , 
                         DPRAM_16x4_Port__numOfPort , DPRAM_16x4_Port__int_clk , 
                         DPRAM_16x4_behave__read1write2 , 
                         DPRAM_16x4_behave__write1read2 , 
                         DPRAM_16x4_behave__write1write2 , 
                         DPRAM_16x4_behave__a_state1 , 
                         DPRAM_16x4_behave__ck_state1 , 
                         DPRAM_16x4_behave__web_state1 , 
                         DPRAM_16x4_behave__oeb_state1 , 
                         DPRAM_16x4_behave__csb_state1 , 
                         DPRAM_16x4_behave__i_state1 , 
                         DPRAM_16x4_behave__o_state1 , 
                         DPRAM_16x4_behave__a_state2 , 
                         DPRAM_16x4_behave__ck_state2 , 
                         DPRAM_16x4_behave__web_state2 , 
                         DPRAM_16x4_behave__oeb_state2 , 
                         DPRAM_16x4_behave__csb_state2 , 
                         DPRAM_16x4_behave__i_state2 , 
                         DPRAM_16x4_behave__o_state2 , 
                         DPRAM_16x4_behave__enable1 , 
                         DPRAM_16x4_behave__blockIsSelected1 , 
                         DPRAM_16x4_behave__sh_a_error_in1 , 
                         DPRAM_16x4_behave__sh_web_error_in1 , 
                         DPRAM_16x4_behave__sh_ba_error_in1 , 
                         DPRAM_16x4_behave__sh_ck_error_in1 , 
                         DPRAM_16x4_behave__sh_csb_error_in1 , 
                         DPRAM_16x4_behave__enable2 , 
                         DPRAM_16x4_behave__blockIsSelected2 , 
                         DPRAM_16x4_behave__sh_a_error_in2 , 
                         DPRAM_16x4_behave__sh_web_error_in2 , 
                         DPRAM_16x4_behave__sh_ba_error_in2 , 
                         DPRAM_16x4_behave__sh_ck_error_in2 , 
                         DPRAM_16x4_behave__sh_csb_error_in2 , 
                         DPRAM_16x4_behave__sh_i_error_in1 , 
                         DPRAM_16x4_behave__sh_i_error_in2 , DPRAM_16x4__A1 , 
                         DPRAM_16x4__A2 , DPRAM_16x4__CE1 , DPRAM_16x4__CE2 , 
                         DPRAM_16x4__WEB1 , DPRAM_16x4__WEB2 , DPRAM_16x4__OEB1 , 
                         DPRAM_16x4__OEB2 , DPRAM_16x4__CSB1 , DPRAM_16x4__CSB2 , 
                         DPRAM_16x4__I1 , DPRAM_16x4__I2 , DPRAM_16x4__O1 , 
                         DPRAM_16x4__O2 );
input   DPRAM_16x4_Port__ck_state , DPRAM_16x4_Port__web_state , 
        DPRAM_16x4_Port__oeb_state , DPRAM_16x4_Port__csb_state , 
        DPRAM_16x4_Port__sh_a_error , DPRAM_16x4_Port__sh_web_error , 
        DPRAM_16x4_Port__sh_ba_error , DPRAM_16x4_Port__sh_ck_error , 
        DPRAM_16x4_Port__sh_csb_error , DPRAM_16x4_Port__sh_i_error , 
        DPRAM_16x4_Port__numOfPort , DPRAM_16x4_behave__read1write2 , 
        DPRAM_16x4_behave__write1read2 , DPRAM_16x4_behave__write1write2 , 
        DPRAM_16x4_behave__ck_state1 , DPRAM_16x4_behave__web_state1 , 
        DPRAM_16x4_behave__oeb_state1 , DPRAM_16x4_behave__csb_state1 , 
        DPRAM_16x4_behave__ck_state2 , DPRAM_16x4_behave__web_state2 , 
        DPRAM_16x4_behave__oeb_state2 , DPRAM_16x4_behave__csb_state2 , 
        DPRAM_16x4_behave__sh_a_error_in1 , DPRAM_16x4_behave__sh_web_error_in1 , 
        DPRAM_16x4_behave__sh_ba_error_in1 , DPRAM_16x4_behave__sh_ck_error_in1 , 
        DPRAM_16x4_behave__sh_csb_error_in1 , DPRAM_16x4_behave__sh_a_error_in2 , 
        DPRAM_16x4_behave__sh_web_error_in2 , DPRAM_16x4_behave__sh_ba_error_in2 , 
        DPRAM_16x4_behave__sh_ck_error_in2 , DPRAM_16x4_behave__sh_csb_error_in2 , 
        DPRAM_16x4_behave__sh_i_error_in1 , DPRAM_16x4_behave__sh_i_error_in2 , 
        DPRAM_16x4__CE1 , DPRAM_16x4__CE2 , DPRAM_16x4__WEB1 , DPRAM_16x4__WEB2 , 
        DPRAM_16x4__OEB1 , DPRAM_16x4__OEB2 , DPRAM_16x4__CSB1 , 
        DPRAM_16x4__CSB2 ;
input   [3:0] DPRAM_16x4_Port__a_state ;
input   [3:0] DPRAM_16x4_Port__i_state ;
input   [3:0] DPRAM_16x4_Port__memoryOut ;
input   [3:0] DPRAM_16x4_behave__a_state1 ;
input   [3:0] DPRAM_16x4_behave__i_state1 ;
input   [3:0] DPRAM_16x4_behave__a_state2 ;
input   [3:0] DPRAM_16x4_behave__i_state2 ;
input   [3:0] DPRAM_16x4__A1 ;
input   [3:0] DPRAM_16x4__A2 ;
input   [3:0] DPRAM_16x4__I1 ;
input   [3:0] DPRAM_16x4__I2 ;
output  DPRAM_16x4_Port__ena_state , DPRAM_16x4_Port__blockIsSelected , 
        DPRAM_16x4_Port__WE , DPRAM_16x4_Port__CS , DPRAM_16x4_Port__int_clk , 
        DPRAM_16x4_behave__enable1 , DPRAM_16x4_behave__blockIsSelected1 , 
        DPRAM_16x4_behave__enable2 , DPRAM_16x4_behave__blockIsSelected2 ;
output  [3:0] DPRAM_16x4_Port__o_state ;
output  [3:0] DPRAM_16x4_Port__memoryAddr ;
output  [3:0] DPRAM_16x4_Port__memoryIn ;
output  [3:0] DPRAM_16x4_behave__o_state1 ;
output  [3:0] DPRAM_16x4_behave__o_state2 ;
output  [3:0] DPRAM_16x4__O1 ;
output  [3:0] DPRAM_16x4__O2 ;

  DPRAM_16x4_Port  DPRAM_16x4_Port ({ DPRAM_16x4_Port__a_state[3:0] } , 
                 DPRAM_16x4_Port__ck_state , DPRAM_16x4_Port__web_state , 
                 DPRAM_16x4_Port__oeb_state , DPRAM_16x4_Port__csb_state , { 
                 DPRAM_16x4_Port__i_state[3:0] } , { 
                 DPRAM_16x4_Port__o_state[3:0] } , DPRAM_16x4_Port__ena_state , 
                 DPRAM_16x4_Port__blockIsSelected , DPRAM_16x4_Port__sh_a_error , 
                 DPRAM_16x4_Port__sh_web_error , DPRAM_16x4_Port__sh_ba_error , 
                 DPRAM_16x4_Port__sh_ck_error , DPRAM_16x4_Port__sh_csb_error , 
                 DPRAM_16x4_Port__sh_i_error , DPRAM_16x4_Port__WE , 
                 DPRAM_16x4_Port__CS , { DPRAM_16x4_Port__memoryAddr[3:0] } , { 
                 DPRAM_16x4_Port__memoryIn[3:0] } , { 
                 DPRAM_16x4_Port__memoryOut[3:0] } , DPRAM_16x4_Port__numOfPort , 
                 DPRAM_16x4_Port__int_clk);
  DPRAM_16x4_behave  DPRAM_16x4_behave (DPRAM_16x4_behave__read1write2 , 
                   DPRAM_16x4_behave__write1read2 , 
                   DPRAM_16x4_behave__write1write2 , { 
                   DPRAM_16x4_behave__a_state1[3:0] } , 
                   DPRAM_16x4_behave__ck_state1 , DPRAM_16x4_behave__web_state1 , 
                   DPRAM_16x4_behave__oeb_state1 , DPRAM_16x4_behave__csb_state1 , 
                   { DPRAM_16x4_behave__i_state1[3:0] } , { 
                   DPRAM_16x4_behave__o_state1[3:0] } , { 
                   DPRAM_16x4_behave__a_state2[3:0] } , 
                   DPRAM_16x4_behave__ck_state2 , DPRAM_16x4_behave__web_state2 , 
                   DPRAM_16x4_behave__oeb_state2 , DPRAM_16x4_behave__csb_state2 , 
                   { DPRAM_16x4_behave__i_state2[3:0] } , { 
                   DPRAM_16x4_behave__o_state2[3:0] } , 
                   DPRAM_16x4_behave__enable1 , 
                   DPRAM_16x4_behave__blockIsSelected1 , 
                   DPRAM_16x4_behave__sh_a_error_in1 , 
                   DPRAM_16x4_behave__sh_web_error_in1 , 
                   DPRAM_16x4_behave__sh_ba_error_in1 , 
                   DPRAM_16x4_behave__sh_ck_error_in1 , 
                   DPRAM_16x4_behave__sh_csb_error_in1 , 
                   DPRAM_16x4_behave__enable2 , 
                   DPRAM_16x4_behave__blockIsSelected2 , 
                   DPRAM_16x4_behave__sh_a_error_in2 , 
                   DPRAM_16x4_behave__sh_web_error_in2 , 
                   DPRAM_16x4_behave__sh_ba_error_in2 , 
                   DPRAM_16x4_behave__sh_ck_error_in2 , 
                   DPRAM_16x4_behave__sh_csb_error_in2 , 
                   DPRAM_16x4_behave__sh_i_error_in1 , 
                   DPRAM_16x4_behave__sh_i_error_in2);
  DPRAM_16x4  DPRAM_16x4 ({ DPRAM_16x4__A1[3:0] } , { DPRAM_16x4__A2[3:0] } , 
            DPRAM_16x4__CE1 , DPRAM_16x4__CE2 , DPRAM_16x4__WEB1 , 
            DPRAM_16x4__WEB2 , DPRAM_16x4__OEB1 , DPRAM_16x4__OEB2 , 
            DPRAM_16x4__CSB1 , DPRAM_16x4__CSB2 , { DPRAM_16x4__I1[3:0] } , { 
            DPRAM_16x4__I2[3:0] } , { DPRAM_16x4__O1[3:0] } , { 
            DPRAM_16x4__O2[3:0] });
endmodule

